### PR TITLE
Define code-cells-move-cell-{up,down}

### PR DESCRIPTION
**Pull request by daanturo**
Allow moving current code cell up and down.
Edit: key bindings aren't decided yet.

### CODE REVIEW

**Comment by astoff** [comment]
I think this is an useful addition.

I'm considering submitting this package to GNU ELPA eventually, so I wanted to check if you signed the FSF copyright papers or are willing to do so. Sorry for not mentioning anything in the Readme (yet).

**Comment by daanturo** [comment]
I have already signed the copyright paper.

**Comment by astoff** [comment]
Sorry for the long delay. Just wanted to check, what is the purpose of the `use-region` argument of `code-cells--bounds-of-cell-relative-from`?

**Comment by daanturo** [comment]
I don't remember it's usage anymore, let's just delete it.

**Comment by astoff** [comment]
Okay, thanks! I'll add keybindings and simplify your code a bit further, I hope you don't mind.

**Pull request merged**
